### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Bellomore** [vitorhnn/livestreamer-gtkmm3#2]
Hi! Thanks! This app is awesome, exactly what I looked for!
I've got 3 suggestions:
First - please, add "Name" field or something like this with editable custom content (may be 3 columns total - name - quality - url). Look at screen below - sometimes its not clear what stream is that urls of afreeca and goodgame.
Second - double click on stream launches edit mode for stream - can you move it to right-click menu? And double click - just for lunching selected stream. 
- remove text from buttons - icons are pretty clear about how it works.
  Thanks again! Good Luck!

The screen (i'm using ubuntu gnome).
http://i.imgur.com/ICINJkd.png

**Comment by vitorhnn** [comment]
Alright, I think d9d4e85 basically contains everything you suggested:
![Preview](http://i.imgur.com/94jRebL.png)

There are a few caveats, though:
- Your streams.list (generally located at ~/XDG_CONFIG_HOME/livestreamer-gtkmm3/) will have to be updated to the new format. `(name;url;quality)`
- The toolbar will _hopefully_ follow whatever your theme's gtk-toolbar-style is set to, but apparently that property [has been deprecated and is "ignored" since GTK+ 3.10](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-toolbar-style), but it's still present in Glade and it still works, so I'm not really sure what's going on there.

**Comment by Bellomore** [comment]
Wow! Thanks! Awesome!
Now it is perfect! 
(toolbar also fine for me, no text)
